name: 💡 General Feature Request
description: Have a new idea/feature? Please suggest!
labels: ["⭐ goal: addition", "status: ✅", "🤩 Up for the grab","enhancement"]
title: "[FEATURE 💡] <description>"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the enhancement you propose.
      placeholder: Enter your description
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Wanna Work upon[y/n] ??
      description: If you want to work on this just say yes or else no. We will assign to someone else.
    validations:
      required: true
