name: Other
description: Use this for any other issues. Please do NOT create blank issues
title: "[OTHER]"
labels: ["✅status: Up for grab, we will disucuss later."]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Wanna Work upon[y/n] ??
      description: If you want to work on this just say yes or else no. We will assign to someone else.
    validations:
      required: true